/**
 * GetAssetHandler — full detail projection for a single asset.
 *
 * Loads in parallel:
 *   1. Asset row with parent / children / category / location
 *   2. Last 10 work orders (summary fields only)
 *   3. PM schedules (active ones only, ordered by nextDue)
 *   4. Attachments (documents) — signed URLs generated by MinIO
 *   5. Lifetime cost aggregation
 *   6. Open WO count + last maintenance date
 *
 * Metrics (MTBF, MTTR, availability) are derived from completed CORRECTIVE
 * work orders directly in this handler to keep the query path self-contained.
 *
 * This is a pure read path — no domain aggregate loading, no Prisma extensions.
 */
import type { PrismaClient } from '@prisma/client'
import type { Client as Minio } from 'minio'
import {
  WorkOrder,
  WorkOrderId,
  WorkOrderStatus,
  Priority,
  AssetMetricsService,
} from '@maintainhub/domain'
import type { WorkOrderProps } from '@maintainhub/domain'
import { DomainException } from '../../../errors/domain.exception.js'
import type { TenantClient } from '../../../lib/tenant-prisma.js'
import type {
  QueryContext,
  AssetDetail,
  AssetStub,
  WorkOrderSummaryDto,
  PMScheduleSummaryDto,
  AssetDocumentDto,
  AssetMetricsSummary,
  AssetCardDto,
} from './query.types.js'

// ── Query ─────────────────────────────────────────────────────────────────────

export interface GetAssetQuery {
  assetId: string
}

// ── Constants ─────────────────────────────────────────────────────────────────

const SIGNED_URL_TTL = 3600 // 1 hour
const RECENT_WO_LIMIT = 10

// ── Handler ───────────────────────────────────────────────────────────────────

export class GetAssetHandler {
  private readonly db: TenantClient

  private readonly prisma: PrismaClient

  private readonly minio: Minio

  private readonly bucket: string

  constructor(db: TenantClient, prisma: PrismaClient, minio: Minio, bucket: string) {
    this.db = db
    this.prisma = prisma
    this.minio = minio
    this.bucket = bucket
  }

  /**
   * @throws DomainException NOT_FOUND
   */
  async handle(query: GetAssetQuery, _ctx: QueryContext): Promise<AssetDetail> {
    // ── 1. Load asset with relations ──────────────────────────────────────────
    const row = await this.db.asset.findFirst({
      where: { id: query.assetId, deletedAt: null },
      include: {
        category: { select: { id: true, code: true, name: true } },
        location: { select: { id: true, code: true, name: true } },
        parent: { select: { id: true, assetNumber: true, name: true } },
        children: {
          where: { deletedAt: null },
          select: { id: true, assetNumber: true, name: true, status: true, criticality: true },
          orderBy: { assetNumber: 'asc' },
        },
      },
    })

    if (!row) {
      throw new DomainException('Asset not found', 'NOT_FOUND', 404)
    }

    // ── 2. Parallel data fetches ──────────────────────────────────────────────
    const [recentWOs, pmSchedules, attachments, costAgg, openWOCount, metricsWOs] =
      await Promise.all([
        // Last N work orders — summary projection
        this.db.workOrder.findMany({
          where: { assetId: query.assetId, deletedAt: null },
          orderBy: { createdAt: 'desc' },
          take: RECENT_WO_LIMIT,
          select: {
            id: true,
            woNumber: true,
            title: true,
            type: true,
            status: true,
            priority: true,
            startedAt: true,
            completedAt: true,
            totalLaborCost: true,
            totalPartsCost: true,
          },
        }),

        // PM schedules — active ones ordered by nextDue
        this.db.pMSchedule.findMany({
          where: { assetId: query.assetId, isActive: true },
          orderBy: { nextDue: 'asc' },
          select: { id: true, title: true, triggerType: true, nextDue: true, isActive: true },
        }),

        // Asset documents (attachments scoped to this asset)
        this.db.attachment.findMany({
          where: { assetId: query.assetId },
          orderBy: { createdAt: 'asc' },
          select: {
            id: true,
            fileName: true,
            mimeType: true,
            fileSize: true,
            storageKey: true,
            createdAt: true,
          },
        }),

        // Lifetime cost aggregation
        this.prisma.workOrder.aggregate({
          where: { assetId: query.assetId, tenantId: row.tenantId, deletedAt: null },
          // eslint-disable-next-line no-underscore-dangle
          _sum: { totalLaborCost: true, totalPartsCost: true },
        }),

        // Open WO count
        this.db.workOrder.count({
          where: {
            assetId: query.assetId,
            deletedAt: null,
            status: { notIn: ['COMPLETED', 'CANCELLED'] },
          },
        }),

        // CORRECTIVE WOs for metrics — load minimal fields
        this.prisma.workOrder.findMany({
          where: {
            assetId: query.assetId,
            tenantId: row.tenantId,
            type: 'CORRECTIVE',
            status: 'COMPLETED',
            deletedAt: null,
            completedAt: { not: null },
          },
          orderBy: { completedAt: 'asc' },
          select: {
            id: true,
            tenantId: true,
            woNumber: true,
            type: true,
            status: true,
            assetId: true,
            createdById: true,
            startedAt: true,
            completedAt: true,
            createdAt: true,
            updatedAt: true,
          },
        }),
      ])

    // ── 3. Generate signed URLs for documents ─────────────────────────────────
    const documents: AssetDocumentDto[] = await Promise.all(
      attachments.map(async (a) => {
        const signedUrl = await this.minio
          .presignedGetObject(this.bucket, a.storageKey, SIGNED_URL_TTL)
          .catch(() => '') // non-fatal — return empty string on MinIO error

        return {
          id: a.id,
          fileName: a.fileName,
          mimeType: a.mimeType,
          fileSize: a.fileSize,
          storageKey: a.storageKey,
          signedUrl,
          uploadedAt: a.createdAt.toISOString(),
        }
      }),
    )

    // ── 4. Compute metrics via AssetMetricsService ────────────────────────────
    const domainWOs = metricsWOs.map((r) =>
      WorkOrder.reconstitute({
        id: new WorkOrderId(r.id),
        tenantId: r.tenantId,
        woNumber: r.woNumber,
        title: '',
        type: r.type as 'CORRECTIVE',
        priority: Priority.from('MEDIUM'),
        status: WorkOrderStatus.COMPLETED,
        assetId: r.assetId,
        createdById: r.createdById,
        createdAt: r.createdAt,
        updatedAt: r.updatedAt,
        ...(r.startedAt !== null && { startedAt: r.startedAt }),
        ...(r.completedAt !== null && { completedAt: r.completedAt }),
      } satisfies WorkOrderProps),
    )

    const mtbf = AssetMetricsService.calculateMTBF(domainWOs)
    const mttr = AssetMetricsService.calculateMTTR(domainWOs)
    const availability = AssetMetricsService.calculateAvailability(0, mtbf, mttr)

    // eslint-disable-next-line no-underscore-dangle
    const sums = costAgg._sum
    const totalLaborCost = sums.totalLaborCost !== null ? Number(sums.totalLaborCost) : 0
    const totalPartsCost = sums.totalPartsCost !== null ? Number(sums.totalPartsCost) : 0

    const metrics: AssetMetricsSummary = {
      mtbfHours: mtbf.hours,
      mtbfDays: mtbf.days,
      mttrHours: mttr.hours,
      mttrDays: mttr.days,
      availability,
      failureCount: domainWOs.length,
      openWorkOrders: openWOCount,
      totalLaborCost,
      totalPartsCost,
      totalLifetimeCost: Math.round((totalLaborCost + totalPartsCost) * 100) / 100,
    }

    // ── 5. Project to DTO ─────────────────────────────────────────────────────
    const now = new Date()
    const warrantyActive = row.warrantyExpiry !== null && row.warrantyExpiry > now

    const children: AssetStub[] = row.children.map((c) => ({
      id: c.id,
      assetNumber: c.assetNumber,
      name: c.name,
      status: c.status,
      criticality: c.criticality,
    }))

    const recentWorkOrders: WorkOrderSummaryDto[] = recentWOs.map((wo) => ({
      id: wo.id,
      woNumber: wo.woNumber,
      title: wo.title,
      type: wo.type,
      status: wo.status,
      priority: wo.priority,
      startedAt: wo.startedAt?.toISOString() ?? null,
      completedAt: wo.completedAt?.toISOString() ?? null,
      totalCost:
        wo.totalLaborCost !== null || wo.totalPartsCost !== null
          ? Math.round((Number(wo.totalLaborCost ?? 0) + Number(wo.totalPartsCost ?? 0)) * 100) /
            100
          : null,
    }))

    const pmDtos: PMScheduleSummaryDto[] = pmSchedules.map((pm) => ({
      id: pm.id,
      title: pm.title,
      triggerType: pm.triggerType,
      nextDue: pm.nextDue?.toISOString() ?? null,
      isActive: pm.isActive,
    }))

    const card: AssetCardDto = {
      id: row.id,
      assetNumber: row.assetNumber,
      name: row.name,
      status: row.status,
      criticality: row.criticality,
      categoryId: row.categoryId,
      categoryName: row.category.name,
      locationId: row.locationId ?? null,
      locationName: row.location?.name ?? null,
      parentId: row.parentId ?? null,
      parentName: row.parent?.name ?? null,
      manufacturer: row.manufacturer ?? null,
      model: row.model ?? null,
      serialNumber: row.serialNumber ?? null,
      installDate: row.installDate?.toISOString() ?? null,
      warrantyExpiry: row.warrantyExpiry?.toISOString() ?? null,
      isWarrantyActive: warrantyActive,
      openWOCount,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    }

    return {
      ...card,
      description: row.description ?? null,
      customFields:
        typeof row.customFields === 'object' && row.customFields !== null
          ? (row.customFields as Record<string, unknown>)
          : {},
      children,
      recentWorkOrders,
      pmSchedules: pmDtos,
      activePMCount: pmSchedules.length,
      nextPMDue: pmSchedules[0]?.nextDue?.toISOString() ?? null,
      documents,
      metrics,
    }
  }
}
