/**
 * GenerateWorkInstructionsUseCase
 *
 * Produces a markdown-formatted, step-by-step maintenance procedure for a work
 * order, tailored to the asset type, WO type, and required technician skills.
 *
 * ## Context provided to Claude
 *
 *   - Work order: title, description, type, priority, failure code
 *   - Asset: name, category, manufacturer/model, criticality, location
 *   - Required skills from any related PM schedule (if WO type is PREVENTIVE)
 *   - Assigned technician count (so instructions can reference "the team" vs
 *     "you" appropriately)
 *
 * ## Output
 *
 *   A single markdown string with:
 *   - Safety warnings block (⚠️)
 *   - Required tools and PPE
 *   - Numbered step-by-step procedure
 *   - Completion checklist
 *   - Reference notes (torque specs, part numbers, etc.)
 */
import type { PrismaClient } from '@prisma/client'
import {
  AI_MODEL,
  AI_MAX_TOKENS,
  AiError,
  extractText,
  recordUsage,
  noopMonitoring,
} from './ai.types.js'
import type { AnthropicClient, MonitoringPort } from './ai.types.js'
import { DomainException } from '../../../errors/domain.exception.js'

// ── Input / Output ────────────────────────────────────────────────────────────

export interface GenerateWorkInstructionsInput {
  workOrderId: string
  tenantId: string
}

export interface WorkInstructionsResult {
  /** Markdown-formatted procedure generated by Claude. */
  procedure: string
  /** WO number included for display in the UI. */
  woNumber: string
  /** Asset name included for display context. */
  assetName: string
}

// ── System prompt ─────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a senior maintenance engineer creating work instructions for a CMMS (Computerised Maintenance Management System).

Generate a clear, professional, step-by-step maintenance procedure in Markdown format.

Your response MUST be formatted exactly as follows (use these exact section headings):

## ⚠️ Safety Warnings
List all safety hazards and required lock-out/tag-out (LOTO) steps.

## Required Tools & PPE
- Tools: [list]
- PPE: [list]

## Procedure
1. Step one
2. Step two
...

## Completion Checklist
- [ ] Item 1
- [ ] Item 2
...

## Reference Notes
Any torque specs, part numbers, clearances, or standards references.

Guidelines:
- Be specific and technical; reference manufacturer specs where relevant
- Include exact torque values, clearances, and settings where known
- Flag any step that requires a second person or specialised equipment
- Prioritise safety — LOTO must appear before any mechanical work
- For EMERGENCY type WOs, add an "Immediate Actions" section before safety warnings
- Keep steps concise but unambiguous; one action per step`

// ── Internal types ────────────────────────────────────────────────────────────

type WoForInstructions = {
  woNumber: string
  title: string
  description: string | null
  type: string
  priority: string
  assigneeIds: string[]
  asset: {
    name: string
    criticality: string
    manufacturer: string | null
    model: string | null
    serialNumber: string | null
    description: string | null
    category: { name: string }
    location: { name: string } | null
    pmSchedules: Array<{
      requiredSkills: string[]
      estimatedHours: unknown
      taskList: unknown
    }>
  }
  failureCode: {
    code: string
    name: string
    category: string
    notes: string | null
  } | null
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function buildUserContent(wo: WoForInstructions): string {
  const a = wo.asset
  const parts: string[] = []

  parts.push('Generate work instructions for the following work order:')
  parts.push('')
  parts.push(`**WO Number:** ${wo.woNumber}`)
  parts.push(`**Type:** ${wo.type} | **Priority:** ${wo.priority}`)
  parts.push(`**Title:** ${wo.title}`)
  if (wo.description) parts.push(`**Description:** ${wo.description}`)

  parts.push('')
  parts.push('**Asset Information:**')
  parts.push(`- Name: ${a.name}`)
  parts.push(`- Category: ${a.category.name}`)
  if (a.location) parts.push(`- Location: ${a.location.name}`)
  if (a.manufacturer ?? a.model) {
    parts.push(`- Equipment: ${[a.manufacturer, a.model].filter(Boolean).join(' ')}`)
  }
  if (a.serialNumber) parts.push(`- Serial No: ${a.serialNumber}`)
  parts.push(`- Criticality: ${a.criticality}`)
  if (a.description) parts.push(`- Notes: ${a.description}`)

  if (wo.failureCode) {
    parts.push('')
    parts.push('**Failure Mode:**')
    parts.push(
      `- Code: ${wo.failureCode.code} — ${wo.failureCode.name} (${wo.failureCode.category})`,
    )
    if (wo.failureCode.notes) parts.push(`- Notes: ${wo.failureCode.notes}`)
  }

  const pm = a.pmSchedules[0]
  if (pm && pm.requiredSkills.length > 0) {
    parts.push('')
    parts.push(`**Required Skills:** ${pm.requiredSkills.join(', ')}`)
  }
  if (pm && typeof pm.estimatedHours === 'number') {
    parts.push(`**Estimated Duration:** ${pm.estimatedHours} hours`)
  }

  // Hint about team size
  const techCount = wo.assigneeIds.length
  if (techCount > 1) {
    parts.push(`**Team size:** ${techCount} technicians assigned`)
  }

  return parts.join('\n')
}

// ── Use case ──────────────────────────────────────────────────────────────────

export class GenerateWorkInstructionsUseCase {
  private readonly prisma: PrismaClient

  private readonly ai: AnthropicClient

  private readonly monitoring: MonitoringPort

  constructor(
    prisma: PrismaClient,
    ai: AnthropicClient,
    monitoring: MonitoringPort = noopMonitoring,
  ) {
    this.prisma = prisma
    this.ai = ai
    this.monitoring = monitoring
  }

  /**
   * @throws DomainException NOT_FOUND when work order does not exist
   * @throws AiError AI_API_ERROR on Anthropic API failure
   * @throws AiError AI_PARSE_ERROR on empty response
   */
  async execute(input: GenerateWorkInstructionsInput): Promise<WorkInstructionsResult> {
    // ── 1. Load work order + asset + optional PM schedule ─────────────────────
    const wo = await this.prisma.workOrder.findFirst({
      where: {
        id: input.workOrderId,
        tenantId: input.tenantId,
        deletedAt: null,
      },
      select: {
        id: true,
        woNumber: true,
        title: true,
        description: true,
        type: true,
        priority: true,
        assigneeIds: true,
        assetId: true,
        asset: {
          select: {
            name: true,
            criticality: true,
            manufacturer: true,
            model: true,
            serialNumber: true,
            description: true,
            category: { select: { name: true } },
            location: { select: { name: true } },
            pmSchedules: {
              where: { isActive: true },
              take: 1,
              select: { requiredSkills: true, estimatedHours: true, taskList: true },
            },
          },
        },
        failureCode: { select: { code: true, name: true, category: true, notes: true } },
      },
    })

    if (!wo) {
      throw new DomainException('Work order not found', 'NOT_FOUND', 404)
    }

    // ── 2. Build prompt ───────────────────────────────────────────────────────
    const userContent = buildUserContent(wo)

    // ── 3. Call Claude ────────────────────────────────────────────────────────
    let message
    try {
      message = await this.ai.messages.create({
        model: AI_MODEL,
        max_tokens: AI_MAX_TOKENS,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: userContent }],
      })
    } catch (err) {
      throw new AiError(
        `Anthropic API error: ${err instanceof Error ? err.message : String(err)}`,
        'AI_API_ERROR',
      )
    }

    // ── 4. Record token usage ─────────────────────────────────────────────────
    recordUsage(this.monitoring, 'GenerateWorkInstructions', message)

    // ── 5. Extract markdown ───────────────────────────────────────────────────
    const procedure = extractText(message).trim()

    return {
      procedure,
      woNumber: wo.woNumber,
      assetName: wo.asset.name,
    }
  }
}
